# fly.toml app configuration file generated for weightcalc on 2024-11-21T20:55:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'food-weight-calculator'
primary_region = 'cdg'

[build]
  [build.args]
    GO_VERSION = '1.23.1'

[env]
  PORT = '8080'
  ENV = 'PROD'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
